# Generated by Django 6.0.3 on 2026-04-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, default='', help_text='Locality / area derived from the pincode.', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(blank=True, default='', help_text="6-digit NCR pincode of the user's location.", max_length=6),
        ),
    ]
