# Generated by Django 6.0.3 on 2026-04-05 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_area_remove_user_area_remove_user_pincode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='expecteddisease',
            name='user',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Area associated with the user, derived from pincode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_area', to='doctor.area'),
        ),
        migrations.CreateModel(
            name='SymptomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.area')),
                ('diseases', models.ManyToManyField(blank=True, to='doctor.disease')),
                ('symptoms', models.ManyToManyField(to='doctor.symptom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ConfirmedDisease',
        ),
        migrations.DeleteModel(
            name='ExpectedDisease',
        ),
    ]
