# Generated by Django 6.0.3 on 2026-04-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0004_disease_remove_expecteddisease_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="symptomreport",
            name="other_symptoms",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="symptomreport",
            name="severity",
            field=models.CharField(
                choices=[("mild", "Mild"), ("moderate", "Moderate"), ("severe", "Severe")],
                default="mild",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
